spring.application.name=demo
# 1. Endereço do banco (troque 'nome_do_seu_banco' pelo nome que você criou no pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/V-agro

# 2. Seu usuário do Postgres (o padrão é postgres)
spring.datasource.username=postgres

# 3. A senha que você definiu quando instalou o Postgres
spring.datasource.password=admin

# 4. Driver que faz a conexão
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. Configuração mágica: o Java cria as tabelas para você automaticamente
spring.jpa.hibernate.ddl-auto=update

# 6. Para ver no console os comandos que o Java está mandando para o banco
spring.jpa.show-sql=true